// Code generated by "stringer -type ValueTypeIdentifier"; DO NOT EDIT.

package util

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Null-0]
	_ = x[Integer-1]
	_ = x[Float-2]
	_ = x[String-3]
	_ = x[Boolean-4]
}

const _ValueTypeIdentifier_name = "NullIntegerFloatStringBoolean"

var _ValueTypeIdentifier_index = [...]uint8{0, 4, 11, 16, 22, 29}

func (i ValueTypeIdentifier) String() string {
	if i < 0 || i >= ValueTypeIdentifier(len(_ValueTypeIdentifier_index)-1) {
		return "ValueTypeIdentifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueTypeIdentifier_name[_ValueTypeIdentifier_index[i]:_ValueTypeIdentifier_index[i+1]]
}
